#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import tempfile
import urllib.error
import urllib.request
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_BUNDLE_DIR = REPO_ROOT / "dist" / "squadds-ml-inference-api"
DEFAULT_ENV_FILE = Path("/Users/shanto/LFL/SQuADDS/SQuADDS/.env")
DEFAULT_SPACE_ID = "SQuADDS/squadds-ml-inference-api"


def parse_env_file(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    for raw_line in path.read_text().splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.replace("export ", "").strip()
        value = value.strip().strip('"').strip("'")
        values[key] = value
    return values


def resolve_token(env_file: Path | None) -> str:
    token = os.getenv("HUGGINGFACE_API_KEY")
    if token:
        return token
    if env_file and env_file.exists():
        token = parse_env_file(env_file).get("HUGGINGFACE_API_KEY")
        if token:
            return token
    raise RuntimeError(
        "HUGGINGFACE_API_KEY is not available. Export it or pass a valid --env-file."
    )


def ensure_space_exists(token: str, space_id: str) -> None:
    org, name = space_id.split("/", 1)
    payload = {
        "name": name,
        "organization": org,
        "private": False,
        "type": "space",
        "sdk": "docker",
    }
    request = urllib.request.Request(
        "https://huggingface.co/api/repos/create",
        data=json.dumps(payload).encode("utf-8"),
        headers={
            "Authorization": f"Bearer {token}",
            "Content-Type": "application/json",
        },
        method="POST",
    )
    try:
        with urllib.request.urlopen(request) as response:
            print(f"Created Space {space_id}: HTTP {response.status}")
    except urllib.error.HTTPError as exc:
        if exc.code == 409:
            print(f"Space {space_id} already exists.")
            return
        body = exc.read().decode("utf-8", errors="replace")
        raise RuntimeError(f"Failed to create Space {space_id}: {exc.code} {body}") from exc


def run(cmd: list[str], cwd: Path | None = None) -> None:
    subprocess.run(cmd, cwd=cwd, check=True)


def publish_bundle(bundle_dir: Path, token: str, space_id: str) -> None:
    remote_url = f"https://__token__:{token}@huggingface.co/spaces/{space_id}"
    with tempfile.TemporaryDirectory(prefix="hf-space-publish-") as tmp:
        clone_dir = Path(tmp) / "space"
        run(["git", "clone", remote_url, str(clone_dir)])

        for item in clone_dir.iterdir():
            if item.name == ".git":
                continue
            if item.is_dir():
                shutil.rmtree(item)
            else:
                item.unlink()

        for item in bundle_dir.iterdir():
            destination = clone_dir / item.name
            if item.is_dir():
                shutil.copytree(item, destination)
            else:
                shutil.copy2(item, destination)

        run(["git", "add", "."], cwd=clone_dir)
        diff = subprocess.run(
            ["git", "status", "--short"],
            cwd=clone_dir,
            capture_output=True,
            text=True,
            check=True,
        )
        if not diff.stdout.strip():
            print("No changes to publish.")
            return

        run(["git", "config", "user.name", "Codex"], cwd=clone_dir)
        run(["git", "config", "user.email", "codex@openai.com"], cwd=clone_dir)
        run(["git", "commit", "-m", "Deploy SQuADDS ML inference API"], cwd=clone_dir)
        run(["git", "push", "origin", "main"], cwd=clone_dir)
        print(f"Published bundle from {bundle_dir} to https://huggingface.co/spaces/{space_id}")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Create or update the SQuADDS Hugging Face Docker Space."
    )
    parser.add_argument(
        "--bundle-dir",
        default=str(DEFAULT_BUNDLE_DIR),
        help="Path to a bundle generated by build_hf_space_bundle.py.",
    )
    parser.add_argument(
        "--space-id",
        default=DEFAULT_SPACE_ID,
        help="Destination Hugging Face Space ID in org/name format.",
    )
    parser.add_argument(
        "--env-file",
        default=str(DEFAULT_ENV_FILE),
        help="Optional .env file containing HUGGINGFACE_API_KEY.",
    )
    args = parser.parse_args()

    bundle_dir = Path(args.bundle_dir).resolve()
    if not bundle_dir.exists():
        raise RuntimeError(
            f"Bundle directory does not exist: {bundle_dir}. Run build_hf_space_bundle.py first."
        )

    env_file = Path(args.env_file).resolve() if args.env_file else None
    token = resolve_token(env_file)
    ensure_space_exists(token, args.space_id)
    publish_bundle(bundle_dir, token, args.space_id)


if __name__ == "__main__":
    main()
